name: scp files
on:
  push:
    branches: [ 'main' ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          #          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./,!README.md,!.github,!.gitignore,!.git"
          #          target: "/opt/easyengine/sites/netider.ch/app/htdocs"
          target: "/htdocs"
          rm: true